---
- name: Install httpd alias
  hosts: prod
  tasks:
  - name: Generate a basic homepage from jinja2 template
    ansible.builtin.copy:
      src: alias.conf
      dest: /var/www/html/index.html
    notify: restart_httpd

  - name: Firewall task
    ansible.posix.firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - http
      - https
      - samba
    notify: restart_firewalld

  handlers:
    - name: restart_httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: yes

    - name: restart_firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
        enabled: yes
